name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup registry
        run: |
          npm config set registry https://artifactory.infrateam.xyz/api/npm/npm/
          npm config set always-auth true
          echo "//artifactory.infrateam.xyz/api/npm/npm/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - uses: ./.github/actions/release
        id: getReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
          ORGANIZATION: Zinchenko-Andrii

      - name: Make dist-tag latest
        if: steps.getReleaseTag.outputs.releaseTag
        run: |
          echo add ${{ steps.getReleaseTag.outputs.packageName }}@${{ steps.getReleaseTag.outputs.releaseTag }}
#          npm dist-tag add ${{ steps.getReleaseTag.outputs.packageName }}@${{ steps.getReleaseTag.outputs.releaseTag }} latest
