name: Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NodeJS setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: HUSKY_SKIP_INSTALL=1 yarn

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          AS_CI: true
        run: npx multi-semantic-release